name: Run Zero to Nix site tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    environment: test
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Check Nixpkgs input
        uses: DeterminateSystems/flake-checker-action@v4
        with:
          fail-mode: true
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Run Nix CI suite
        run: nix develop --command ci
      - name: Check flake templates
        run:
          for env in ./nix/templates/dev/*; do
            nix flake check "${env}"
          done

          for pkg in ./nix/templates/pkg/*; do
            nix build "${pkg}"
          done
