name: Run Zero to Nix site tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      #- name: Set up htmltest cache
      #  uses: actions/cache@v3
      #  with:
      #    key: zero-to-nix-${{ hashFiles('.htmltest.external.yml') }}
      #    path: |
      #      tmp/

      - uses: DeterminateSystems/nix-installer@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            binary-caches = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
            trusted-substituters = https://cache.nixos.org https://${{ secrets.CACHIX_CACHE }}.cachix.org
            trusted-users = root runner
            trusted-public-keys = ${{ secrets.CACHIX_TRUSTED_PUBLIC_KEY }} ${{ secrets.NIXOS_PUBLIC_KEY }}
      - name: Cachix setup
        run: |
          nix develop --command cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
          nix develop --command cachix use ${{ secrets.CACHIX_CACHE }}
      - name: Run Nix CI suite
        run: nix develop --command ci
      - name: Push dev shell to Cachix
        run: |
          nix develop --profile zero-to-nix
          nix develop --command cachix push ${{ secrets.CACHIX_CACHE }} zero-to-nix
